# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Thu Sep 29 14:40:08 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogName(object):
    def setupUi(self, dialogName):
        dialogName.setObjectName(_fromUtf8("dialogName"))
        dialogName.setWindowModality(QtCore.Qt.WindowModal)
        dialogName.resize(464, 640)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialogName.sizePolicy().hasHeightForWidth())
        dialogName.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        dialogName.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Georgia"))
        dialogName.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Imatges/Logos/ESC0701.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Imatges/Logos/ESC0701.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../Imatges/Logos/ESC0701.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        dialogName.setWindowIcon(icon)
        dialogName.setWindowOpacity(10.0)
        dialogName.setAutoFillBackground(True)
        dialogName.setSizeGripEnabled(False)
        dialogName.setModal(True)
        self.lblTitle = QtGui.QLabel(dialogName)
        self.lblTitle.setGeometry(QtCore.QRect(240, 15, 191, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.lblTitle.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Georgia"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.gbUbicacio = QtGui.QGroupBox(dialogName)
        self.gbUbicacio.setGeometry(QtCore.QRect(10, 80, 441, 111))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Georgia"))
        font.setPointSize(10)
        self.gbUbicacio.setFont(font)
        self.gbUbicacio.setObjectName(_fromUtf8("gbUbicacio"))
        self.btnParcelaPdf = QtGui.QPushButton(self.gbUbicacio)
        self.btnParcelaPdf.setGeometry(QtCore.QRect(350, 20, 81, 26))
        self.btnParcelaPdf.setObjectName(_fromUtf8("btnParcelaPdf"))
        self.label = QtGui.QLabel(self.gbUbicacio)
        self.label.setGeometry(QtCore.QRect(20, 20, 101, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.gbUbicacio)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 101, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.gbUbicacio)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 91, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.refcat = QtGui.QLineEdit(self.gbUbicacio)
        self.refcat.setEnabled(False)
        self.refcat.setGeometry(QtCore.QRect(115, 20, 131, 20))
        self.refcat.setObjectName(_fromUtf8("refcat"))
        self.area = QtGui.QLineEdit(self.gbUbicacio)
        self.area.setEnabled(False)
        self.area.setGeometry(QtCore.QRect(115, 50, 81, 20))
        self.area.setObjectName(_fromUtf8("area"))
        self.ninterno = QtGui.QLineEdit(self.gbUbicacio)
        self.ninterno.setEnabled(False)
        self.ninterno.setGeometry(QtCore.QRect(360, 50, 51, 20))
        self.ninterno.setObjectName(_fromUtf8("ninterno"))
        self.label_8 = QtGui.QLabel(self.gbUbicacio)
        self.label_8.setGeometry(QtCore.QRect(210, 50, 31, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.txtAdreca = QtGui.QLineEdit(self.gbUbicacio)
        self.txtAdreca.setEnabled(False)
        self.txtAdreca.setGeometry(QtCore.QRect(115, 80, 316, 20))
        self.txtAdreca.setObjectName(_fromUtf8("txtAdreca"))
        self.gbZones = QtGui.QGroupBox(dialogName)
        self.gbZones.setGeometry(QtCore.QRect(10, 360, 441, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Georgia"))
        font.setPointSize(10)
        self.gbZones.setFont(font)
        self.gbZones.setObjectName(_fromUtf8("gbZones"))
        self.label_4 = QtGui.QLabel(self.gbZones)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 51, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(self.gbZones)
        self.label_6.setGeometry(QtCore.QRect(160, 20, 121, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.gbZones)
        self.label_7.setGeometry(QtCore.QRect(80, 20, 81, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.txtClau_1 = QtGui.QLineEdit(self.gbZones)
        self.txtClau_1.setEnabled(False)
        self.txtClau_1.setGeometry(QtCore.QRect(20, 40, 51, 20))
        self.txtClau_1.setObjectName(_fromUtf8("txtClau_1"))
        self.txtPer_1 = QtGui.QLineEdit(self.gbZones)
        self.txtPer_1.setEnabled(False)
        self.txtPer_1.setGeometry(QtCore.QRect(90, 40, 60, 20))
        self.txtPer_1.setObjectName(_fromUtf8("txtPer_1"))
        self.btnClauPdf_1 = QtGui.QPushButton(self.gbZones)
        self.btnClauPdf_1.setGeometry(QtCore.QRect(350, 30, 81, 26))
        self.btnClauPdf_1.setObjectName(_fromUtf8("btnClauPdf_1"))
        self.txtClau_2 = QtGui.QLineEdit(self.gbZones)
        self.txtClau_2.setEnabled(False)
        self.txtClau_2.setGeometry(QtCore.QRect(20, 70, 51, 20))
        self.txtClau_2.setObjectName(_fromUtf8("txtClau_2"))
        self.txtClau_3 = QtGui.QLineEdit(self.gbZones)
        self.txtClau_3.setEnabled(False)
        self.txtClau_3.setGeometry(QtCore.QRect(20, 100, 51, 20))
        self.txtClau_3.setObjectName(_fromUtf8("txtClau_3"))
        self.lblOrd_1 = QtGui.QLabel(self.gbZones)
        self.lblOrd_1.setGeometry(QtCore.QRect(170, 40, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblOrd_1.setFont(font)
        self.lblOrd_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblOrd_1.setMouseTracking(True)
        self.lblOrd_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblOrd_1.setObjectName(_fromUtf8("lblOrd_1"))
        self.txtPer_2 = QtGui.QLineEdit(self.gbZones)
        self.txtPer_2.setEnabled(False)
        self.txtPer_2.setGeometry(QtCore.QRect(90, 70, 60, 20))
        self.txtPer_2.setObjectName(_fromUtf8("txtPer_2"))
        self.txtPer_3 = QtGui.QLineEdit(self.gbZones)
        self.txtPer_3.setEnabled(False)
        self.txtPer_3.setGeometry(QtCore.QRect(90, 100, 60, 20))
        self.txtPer_3.setObjectName(_fromUtf8("txtPer_3"))
        self.lblOrd_2 = QtGui.QLabel(self.gbZones)
        self.lblOrd_2.setGeometry(QtCore.QRect(170, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblOrd_2.setFont(font)
        self.lblOrd_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblOrd_2.setMouseTracking(True)
        self.lblOrd_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblOrd_2.setObjectName(_fromUtf8("lblOrd_2"))
        self.lblOrd_3 = QtGui.QLabel(self.gbZones)
        self.lblOrd_3.setGeometry(QtCore.QRect(170, 100, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblOrd_3.setFont(font)
        self.lblOrd_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblOrd_3.setMouseTracking(True)
        self.lblOrd_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblOrd_3.setObjectName(_fromUtf8("lblOrd_3"))
        self.txtClau_4 = QtGui.QLineEdit(self.gbZones)
        self.txtClau_4.setEnabled(False)
        self.txtClau_4.setGeometry(QtCore.QRect(20, 130, 51, 20))
        self.txtClau_4.setObjectName(_fromUtf8("txtClau_4"))
        self.txtPer_4 = QtGui.QLineEdit(self.gbZones)
        self.txtPer_4.setEnabled(False)
        self.txtPer_4.setGeometry(QtCore.QRect(90, 130, 60, 20))
        self.txtPer_4.setObjectName(_fromUtf8("txtPer_4"))
        self.lblOrd_4 = QtGui.QLabel(self.gbZones)
        self.lblOrd_4.setGeometry(QtCore.QRect(170, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblOrd_4.setFont(font)
        self.lblOrd_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblOrd_4.setMouseTracking(True)
        self.lblOrd_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblOrd_4.setObjectName(_fromUtf8("lblOrd_4"))
        self.gbAnnex = QtGui.QGroupBox(dialogName)
        self.gbAnnex.setGeometry(QtCore.QRect(10, 530, 441, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Georgia"))
        font.setPointSize(10)
        self.gbAnnex.setFont(font)
        self.gbAnnex.setObjectName(_fromUtf8("gbAnnex"))
        self.lblCondGenerals = QtGui.QLabel(self.gbAnnex)
        self.lblCondGenerals.setGeometry(QtCore.QRect(20, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblCondGenerals.setFont(font)
        self.lblCondGenerals.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblCondGenerals.setMouseTracking(True)
        self.lblCondGenerals.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblCondGenerals.setObjectName(_fromUtf8("lblCondGenerals"))
        self.lblParamFinca = QtGui.QLabel(self.gbAnnex)
        self.lblParamFinca.setGeometry(QtCore.QRect(290, 20, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblParamFinca.setFont(font)
        self.lblParamFinca.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblParamFinca.setMouseTracking(True)
        self.lblParamFinca.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblParamFinca.setObjectName(_fromUtf8("lblParamFinca"))
        self.lblParamEdificacio = QtGui.QLabel(self.gbAnnex)
        self.lblParamEdificacio.setGeometry(QtCore.QRect(290, 40, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblParamEdificacio.setFont(font)
        self.lblParamEdificacio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblParamEdificacio.setMouseTracking(True)
        self.lblParamEdificacio.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblParamEdificacio.setObjectName(_fromUtf8("lblParamEdificacio"))
        self.lblDotacioAparc = QtGui.QLabel(self.gbAnnex)
        self.lblDotacioAparc.setGeometry(QtCore.QRect(20, 40, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblDotacioAparc.setFont(font)
        self.lblDotacioAparc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblDotacioAparc.setMouseTracking(True)
        self.lblDotacioAparc.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblDotacioAparc.setObjectName(_fromUtf8("lblDotacioAparc"))
        self.lblRegulacioAparc = QtGui.QLabel(self.gbAnnex)
        self.lblRegulacioAparc.setGeometry(QtCore.QRect(20, 60, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblRegulacioAparc.setFont(font)
        self.lblRegulacioAparc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblRegulacioAparc.setMouseTracking(True)
        self.lblRegulacioAparc.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblRegulacioAparc.setObjectName(_fromUtf8("lblRegulacioAparc"))
        self.label_5 = QtGui.QLabel(dialogName)
        self.label_5.setGeometry(QtCore.QRect(13, 15, 191, 50))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8("img/ESC0401.png")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gbSector = QtGui.QGroupBox(dialogName)
        self.gbSector.setGeometry(QtCore.QRect(10, 200, 441, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbSector.setFont(font)
        self.gbSector.setObjectName(_fromUtf8("gbSector"))
        self.txtSector = QtGui.QLineEdit(self.gbSector)
        self.txtSector.setEnabled(False)
        self.txtSector.setGeometry(QtCore.QRect(115, 20, 316, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtSector.setFont(font)
        self.txtSector.setObjectName(_fromUtf8("txtSector"))
        self.lblSector = QtGui.QLabel(self.gbSector)
        self.lblSector.setGeometry(QtCore.QRect(250, 45, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblSector.setFont(font)
        self.lblSector.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblSector.setMouseTracking(True)
        self.lblSector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblSector.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSector.setObjectName(_fromUtf8("lblSector"))
        self.label_9 = QtGui.QLabel(self.gbSector)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gbClass = QtGui.QGroupBox(dialogName)
        self.gbClass.setGeometry(QtCore.QRect(10, 280, 441, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbClass.setFont(font)
        self.gbClass.setObjectName(_fromUtf8("gbClass"))
        self.txtClass = QtGui.QLineEdit(self.gbClass)
        self.txtClass.setEnabled(False)
        self.txtClass.setGeometry(QtCore.QRect(115, 20, 316, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtClass.setFont(font)
        self.txtClass.setObjectName(_fromUtf8("txtClass"))
        self.lblClass = QtGui.QLabel(self.gbClass)
        self.lblClass.setGeometry(QtCore.QRect(210, 45, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblClass.setFont(font)
        self.lblClass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblClass.setMouseTracking(True)
        self.lblClass.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblClass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblClass.setObjectName(_fromUtf8("lblClass"))
        self.label_11 = QtGui.QLabel(self.gbClass)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 91, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))

        self.retranslateUi(dialogName)
        QtCore.QMetaObject.connectSlotsByName(dialogName)

    def retranslateUi(self, dialogName):
        dialogName.setWindowTitle(_translate("dialogName", "Sant Joan de Vilatorrada", None))
        self.lblTitle.setText(_translate("dialogName", "Fitxa urbanística", None))
        self.gbUbicacio.setTitle(_translate("dialogName", "Ubicació (dades cadastrals)", None))
        self.btnParcelaPdf.setText(_translate("dialogName", "Obrir PDF", None))
        self.label.setText(_translate("dialogName", "Ref. cadastral:", None))
        self.label_2.setText(_translate("dialogName", "Àrea:", None))
        self.label_3.setText(_translate("dialogName", "Adreça:", None))
        self.label_8.setText(_translate("dialogName", "<html><head/><body><p>m²</p></body></html>", None))
        self.gbZones.setTitle(_translate("dialogName", "Zones planejament", None))
        self.label_4.setText(_translate("dialogName", "Clau", None))
        self.label_6.setText(_translate("dialogName", "Tipus ordenació", None))
        self.label_7.setText(_translate("dialogName", "Percentatge", None))
        self.btnClauPdf_1.setText(_translate("dialogName", "Obrir PDF", None))
        self.lblOrd_1.setText(_translate("dialogName", "<a href=\'condicions_generals.htm\'>ORD</a>", None))
        self.lblOrd_2.setText(_translate("dialogName", "<a href=\'condicions_generals.htm\'>ORD</a>", None))
        self.lblOrd_3.setText(_translate("dialogName", "<a href=\'condicions_generals.htm\'>ORD</a>", None))
        self.lblOrd_4.setText(_translate("dialogName", "<a href=\'condicions_generals.htm\'>ORD</a>", None))
        self.gbAnnex.setTitle(_translate("dialogName", "Annex", None))
        self.lblCondGenerals.setText(_translate("dialogName", "<a href=\'condicions_generals.htm\'>Condicions Generals</a>", None))
        self.lblParamFinca.setText(_translate("dialogName", "<a href=\'param_finca.htm\'>Paràmetres Finca</a>", None))
        self.lblParamEdificacio.setText(_translate("dialogName", "<a href=\'param_edificacio.htm\'>Paràmetres Edificació</a>", None))
        self.lblDotacioAparc.setText(_translate("dialogName", "<a href=\'dotacio_aparcament.htm\'>Dotació mínima d\'aparcaments</a>", None))
        self.lblRegulacioAparc.setText(_translate("dialogName", "<a href=\'regulacio_aparcament.htm\'>Regulació particular de l\'ús d\'aparcaments</a>", None))
        self.gbSector.setTitle(_translate("dialogName", "Sector", None))
        self.lblSector.setText(_translate("dialogName", "<a href=\'condicions_generals.htm\'>Veure Normativa sector</a>", None))
        self.label_9.setText(_translate("dialogName", "Codi - Nom:", None))
        self.gbClass.setTitle(_translate("dialogName", "Classificació", None))
        self.lblClass.setText(_translate("dialogName", "<a href=\'condicions_generals.htm\'>Veure Normativa classificació</a>", None))
        self.label_11.setText(_translate("dialogName", "Codi - Nom:", None))

