-- Funcio que retorna una taula amb tots els valors necesaris pel pdf de les zones
DROP FUNCTION IF EXISTS data.ficha_urbanistica_zones( INT );
CREATE FUNCTION data.ficha_urbanistica_zones(INT)
  RETURNS TABLE(
    qua_codi            CHARACTER VARYING(10),
    qua_descripcio      TEXT,
    area_int            DOUBLE PRECISION,
    per_int             DOUBLE PRECISION,
    qg_tipus            TEXT,
    qg_subzona          TEXT,
    qg_definicio        TEXT,
    tord_codi           TEXT,
    tord_descripcio     TEXT,
    hab_unifamiliar     TEXT,
    hab_plurifamiliar   TEXT,
    hab_rural           TEXT,
    res_especial        TEXT,
    res_mobil           TEXT,
    hoteler             TEXT,
    com_petit           TEXT,
    com_mitja           TEXT,
    com_gran            TEXT,
    oficines_serveis    TEXT,
    restauracio         TEXT,
    recreatiu           TEXT,
    magatzem            TEXT,
    industrial_1        TEXT,
    industrial_2        TEXT,
    industrial_3        TEXT,
    industrial_4        TEXT,
    industrial_5        TEXT,
    taller_reparacio    TEXT,
    educatiu            TEXT,
    sanitari            TEXT,
    assistencial        TEXT,
    cultural            TEXT,
    associatiu          TEXT,
    esportiu            TEXT,
    serveis_publics     TEXT,
    serveis_tecnics     TEXT,
    serveis_ambientals  TEXT,
    serveis_radio       TEXT,
    aparcament          TEXT,
    estacions_servei    TEXT,
    agricola            TEXT,
    ramader             TEXT,
    forestal            TEXT,
    lleure              TEXT,
    ecologic            TEXT,
    fondaria_edif       TEXT,
    edificabilitat      TEXT,
    ocupacio            TEXT,
    densitat_hab        TEXT,
    vol_max_edif        TEXT,
    fondaria_edif_pb    TEXT,
    pb                  TEXT,
    alcada              TEXT,
    punt_aplic          TEXT,
    sep_min             TEXT,
    constr_aux_alcada   TEXT,
    constr_auxo_cupacio TEXT,
    tanques             TEXT,
    nplantes            TEXT,
    alcada_lliure       TEXT,
    entresol_pb         TEXT,
    sotacoberta         TEXT,
    pendent             TEXT,
    terrasses           TEXT,
    elem_sort           TEXT,
    cossos_sort         TEXT,
    cossos_annexes      TEXT,
    porxos              TEXT,
    tract_facana        TEXT,
    comp_facana         TEXT,
    prop_obertura       TEXT,
    material_facana     TEXT,
    material_coberta    TEXT,
    fusteria            TEXT,
    espai_lliure        TEXT,
    altell              TEXT,
    altres              TEXT,
    front_min           TEXT,
    parce_min           TEXT,
    prof_min            TEXT
  ) AS $$

SELECT
  quali.codi       AS qua_codi,
  quali.descripcio AS qua_descripcio,
  quali.area       AS area_int,
  quali.percent    AS per_int,
  qg.tipus_qualif  AS qg_tipus,
  qg.subzona       AS qg_subzona,
  qg.definicio     AS qg_definicio,
  tord.cod_ord     AS tord_codi,
  tord.tipus_ord   AS tord_descripcio,
  hab_unifamiliar,
  hab_plurifamiliar,
  hab_rural,
  res_especial,
  res_mobil,
  hoteler,
  com_petit,
  com_mitja,
  com_gran,
  oficines_serveis,
  restauracio,
  recreatiu,
  magatzem,
  industrial_1,
  industrial_2,
  industrial_3,
  industrial_4,
  industrial_5,
  taller_reparacio,
  educatiu,
  sanitari,
  assistencial,
  cultural,
  associatiu,
  esportiu,
  serveis_publics,
  serveis_tecnics,
  serveis_ambientals,
  serveis_radio,
  aparcament,
  estacions_servei,
  agricola,
  ramader,
  forestal,
  lleure,
  ecologic,
  fondaria_edif,
  edificabilitat,
  ocupacio,
  densitat_hab,
  vol_max_edif,
  fondaria_edif_pb,
  pb,
  alcada,
  punt_aplic,
  sep_min,
  constr_aux_alcada,
  constr_auxo_cupacio,
  tanques,
  nplantes,
  alcada_lliure,
  entresol_pb,
  sotacoberta,
  pendent,
  terrasses,
  elem_sort,
  cossos_sort,
  cossos_annexes,
  porxos,
  tract_facana,
  comp_facana,
  prop_obertura,
  material_facana,
  material_coberta,
  fusteria,
  espai_lliure,
  altell,
  altres,
  front_min,
  parce_min,
  prof_min
FROM
  (
    WITH
        _parcela AS (
          SELECT
            geom,
            ST_Area(geom) AS area
          FROM carto.parcela
          WHERE ninterno = $1
          LIMIT 1
      )
    SELECT
      quali.codi,
      quali.descripcio,
      quali.area,
      100 * quali.area / _parcela.area AS percent
    FROM
      (SELECT
         quali.codi,
         MAX(quali.descripcio)                                   AS descripcio,
         SUM(ST_Area(ST_Intersection(parcela.geom, quali.geom))) AS area
       FROM
         carto.qualificacions AS quali,
         _parcela AS parcela
       WHERE ST_Intersects(parcela.geom, quali.geom)
       GROUP BY quali.codi) quali,
      _parcela
  ) AS quali
  JOIN data.qualificacio_general AS qg ON quali.codi = qg.id
  LEFT JOIN data.tipus_ordenacio AS tord ON qg.cod_ord = tord.cod_ord
  LEFT JOIN data.usos ON qg.id = usos.id
  LEFT JOIN data.condicions_edif ON qg.id = condicions_edif.id
  LEFT JOIN data.condicions_parce ON qg.id = data.condicions_parce.id
WHERE percent >= 3
ORDER BY percent DESC
LIMIT 4;

$$ LANGUAGE SQL;