-- Funcio que retorna una taula amb tots els valors necesaris pel pdf de les zones
CREATE OR REPLACE FUNCTION data.ficha_urbanistica_zones(int) RETURNS TABLE(
  qua_codi character varying(10),
  qua_descripcio text,
  area_int double precision,
  per_int double precision,
  qg_tipus text,
  qg_subzona text,
  qg_definicio text,
  tord_codi text,
  tord_descripcio text,
  hab_unifamiliar text,
  hab_plurifamiliar text,
  hab_rural text,
  res_especial text,
  res_mobil text,
  hoteler text,
  com_petit text,
  com_mitja text,
  com_gran text,
  oficines_serveis text,
  restauracio text,
  recreatiu text,
  magatzem text,
  industrial_1 text,
  industrial_2 text,
  industrial_3 text,
  industrial_4 text,
  industrial_5 text,
  taller_reparacio text,
  educatiu text,
  sanitari text,
  assistencial text,
  cultural text,
  associatiu text,
  esportiu text,
  serveis_publics text,
  serveis_tecnics text,
  serveis_ambientals text,
  serveis_radio text,
  aparcament text,
  estacions_servei text,
  agricola text,
  ramader text,
  forestal text,
  lleure text,
  ecologic text,
  fondaria_edif text,
  edificabilitat text,
  ocupacio text,
  densitat_hab text,
  vol_max_edif text,
  fondaria_edif_pb text,
  pb text,
  alcada text,
  punt_aplic text,
  sep_min text,
  constr_aux_alcada text,
  constr_auxo_cupacio text,
  tanques text,
  nplantes text,
  alcada_lliure text,
  entresol_pb text,
  sotacoberta text,
  pendent text,
  terrasses text,
  elem_sort text,
  cossos_sort text,
  cossos_annexes text,
  porxos text,
  tract_facana text,
  comp_facana text,
  prop_obertura text,
  material_facana text,
  material_coberta text,
  fusteria text,
  espai_lliure text,
  altell text,
  altres text,
  front_min text,
  parce_min text,
  prof_min text
) AS $$

SELECT qua.codi AS qua_codi, qua.descripcio AS qua_descripcio, ST_Area(ST_Multi(ST_Intersection(parcela.geom, qua.geom))) AS area_int, (ST_Area(ST_Multi(ST_Intersection(parcela.geom, qua.geom))) / parcela.area)*100 as per_int, qg.tipus_qualif AS qg_tipus, qg.subzona AS qg_subzona, qg.definicio AS qg_definicio, tord.cod_ord AS tord_codi, tord.tipus_ord AS tord_descripcio, hab_unifamiliar, hab_plurifamiliar, hab_rural, res_especial, res_mobil, hoteler, com_petit, com_mitja, com_gran,
       oficines_serveis, restauracio, recreatiu, magatzem, industrial_1, industrial_2, industrial_3, industrial_4, industrial_5,
       taller_reparacio, educatiu, sanitari, assistencial, cultural, associatiu, esportiu, serveis_publics, serveis_tecnics,
       serveis_ambientals, serveis_radio, aparcament, estacions_servei, agricola, ramader, forestal, lleure, ecologic,
       fondaria_edif, edificabilitat, ocupacio, densitat_hab, vol_max_edif, fondaria_edif_pb, pb, alcada, punt_aplic, sep_min, 
       constr_aux_alcada, constr_auxo_cupacio, tanques, nplantes, alcada_lliure, entresol_pb, sotacoberta, pendent,
       terrasses, elem_sort, cossos_sort, cossos_annexes, porxos, tract_facana, comp_facana, prop_obertura, material_facana,
       material_coberta, fusteria, espai_lliure, altell, altres, front_min, parce_min, prof_min
  FROM carto.parcela AS parcela, carto.qualificacions AS qua
       INNER JOIN data.qualificacio_general AS qg ON qua.codi = qg.id
       LEFT JOIN data.tipus_ordenacio AS tord ON qg.cod_ord = tord.cod_ord
       LEFT JOIN data.usos ON qg.id = usos.id
       LEFT JOIN data.condicions_edif ON qg.id = condicions_edif.id
       LEFT JOIN data.condicions_parce ON qg.id = data.condicions_parce.id
  WHERE parcela.ninterno = $1
        AND ST_Intersects(parcela.geom, qua.geom)
  ORDER BY area_int DESC
  LIMIT 4

$$ LANGUAGE SQL;